version: "3"
services:
  progcon:
    build: .
    image: jpeddicord/progcon:latest
    network_mode: host
    volumes:
      - ./docker/data/conf:/opt/progcon/conf
      - ./docker/data/problems:/opt/progcon-problems
      - ./docker/data/logs:/opt/progcon/logs
