[package]
name = "progcon-bot"
version = "0.1.0"
authors = ["Jacob Peddicord <jacob@peddicord.net>"]

[dependencies]
env_logger = "0.3.3"
log = "0.3.6"
nanomsg = "0.5.0"
rustc-serialize = "0.3.19"
tempdir = "0.3.4"
toml = "0.1.30"
